import * as Factory from "factory.ts";
import Theme from "../../models/theme";
import { faker } from '@faker-js/faker';

export const themeModeFactory = Factory.Sync.makeFactory<Theme>(() => ({
    primary: faker.color.human(),
    primaryLighten5: faker.color.human(),
    primaryLighten4: faker.color.human(),
    primaryLighten3: faker.color.human(),
    primaryLighten2: faker.color.human(),
    primaryLighten1: faker.color.human(),
    primaryDarken1: faker.color.human(),
    primaryDarken2: faker.color.human(),
    primaryDarken3: faker.color.human(),
    primaryDarken4: faker.color.human(),
    primaryDarken5: faker.color.human(),

    secondary: faker.color.human(),
    secondaryLighten5: faker.color.human(),
    secondaryLighten4: faker.color.human(),
    secondaryLighten3: faker.color.human(),
    secondaryLighten2: faker.color.human(),
    secondaryLighten1: faker.color.human(),
    secondaryDarken1: faker.color.human(),
    secondaryDarken2: faker.color.human(),
    secondaryDarken3: faker.color.human(),
    secondaryDarken4: faker.color.human(),
    secondaryDarken5: faker.color.human(),

    error: faker.color.human(),
    errorLighten5: faker.color.human(),
    errorLighten4: faker.color.human(),
    errorLighten3: faker.color.human(),
    errorLighten2: faker.color.human(),
    errorLighten1: faker.color.human(),
    errorDarken1: faker.color.human(),
    errorDarken2: faker.color.human(),
    errorDarken3: faker.color.human(),
    errorDarken4: faker.color.human(),
    errorDarken5: faker.color.human(),

    grey: faker.color.human(),
    greyLighten5: faker.color.human(),
    greyLighten4: faker.color.human(),
    greyLighten3: faker.color.human(),
    greyLighten2: faker.color.human(),
    greyLighten1: faker.color.human(),
    greyDarken1: faker.color.human(),
    greyDarken2: faker.color.human(),
    greyDarken3: faker.color.human(),
    greyDarken4: faker.color.human(),
    greyDarken5: faker.color.human(),

    black: faker.color.human(),
    white: faker.color.human(),
}));
